export const fallbackGameImage = "/img/games/mobile-legends.webp";

export const gamesData = [
  {
    id: "mobile-legends",
    name: "Mobile Legends",
    subtitle: "Mobile Legends",
    image: "/img/games/mobile-legends.webp",
    icon: "M",
    bgColor: "from-blue-400 to-blue-600",
    coinName: "Diamonds",
  },
  {
    id: "honor-of-kings",
    name: "Honor Of Kings",
    subtitle: "Honor Of Kings",
    image: "/img/games/honor-of-kings.jpg",
    icon: "H",
    bgColor: "from-yellow-400 to-amber-600",
    coinName: "Tokens",
  },
  {
    id: "pubg-global",
    name: "PUBG Global",
    subtitle: "PUBG Global",
    image: "/img/games/honor-of-kings.jpg",
    icon: "P",
    bgColor: "from-orange-400 to-red-500",
    coinName: "UC",
  },
  {
    id: "genshin-impact",
    name: "Genshin Impact",
    subtitle: "Genshin Impact",
    image: "/img/games/mobile-legends.webp",
    icon: "G",
    bgColor: "from-purple-400 to-pink-500",
    coinName: "Crystals",
  },
  {
    id: "clash-of-clans",
    name: "Clash of Clans",
    subtitle: "Clash Of Clans",
    image: "/img/games/honor-of-kings.jpg",
    icon: "C",
    bgColor: "from-yellow-400 to-orange-500",
    coinName: "Gems",
  },
  {
    id: "honkai-star-rail",
    name: "Honkai: Star Rail",
    subtitle: "Honkai Star Rail",
    image: "/img/games/mobile-legends.webp",
    icon: "H",
    bgColor: "from-indigo-400 to-purple-500",
    coinName: "Stellar Jades",
  },
  {
    id: "clash-royale",
    name: "Clash Royale",
    subtitle: "Clash Royale",
    image: "/img/games/honor-of-kings.jpg",
    icon: "R",
    bgColor: "from-red-400 to-pink-500",
    coinName: "Gems",
  },
  {
    id: "farlight-84",
    name: "Farlight 84",
    subtitle: "Farlight 84",
    image: "/img/games/mobile-legends.webp",
    icon: "F",
    bgColor: "from-green-400 to-teal-500",
    coinName: "Gold",
  },
  {
    id: "free-fire",
    name: "Free Fire",
    subtitle: "Free Fire",
    image: "/img/games/honor-of-kings.jpg",
    icon: "F",
    bgColor: "from-red-500 to-orange-500",
    coinName: "Diamonds",
  },
  {
    id: "call-of-duty",
    name: "Call of Duty",
    subtitle: "Call Of Duty",
    image: "/img/games/mobile-legends.webp",
    icon: "C",
    bgColor: "from-gray-600 to-gray-800",
    coinName: "CP",
  },
  {
    id: "valorant",
    name: "Valorant",
    subtitle: "Valorant",
    image: "/img/games/honor-of-kings.jpg",
    icon: "V",
    bgColor: "from-red-600 to-pink-600",
    coinName: "VP",
  },
  {
    id: "apex-legends",
    name: "Apex Legends",
    subtitle: "Apex Legends",
    image: "/img/games/mobile-legends.webp",
    icon: "A",
    bgColor: "from-orange-500 to-red-600",
    coinName: "Coins",
  },
  {
    id: "fortnite",
    name: "Fortnite",
    subtitle: "Fortnite",
    image: "/img/games/honor-of-kings.jpg",
    icon: "F",
    bgColor: "from-purple-500 to-blue-500",
    coinName: "V-Bucks",
  },
];
